<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE listaClientes [
    <!ELEMENT listaClientes (cliente+)>
    <!ELEMENT cliente (nombre,diasentrega+)>
    <!ATTLIST cliente cif CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT diasentrega (#PCDATA)>
]>

<listaClientes>
    <cliente cif="5676443B">
        <nombre>Mercasa</nombre>
        <diasentrega>Lunes</diasentrega>
        <diasentrega>Martes</diasentrega>
    </cliente>

    <cliente cif="5121554B">
        <nombre>Acer SL</nombre>
        <diasentrega>Lunes</diasentrega>
    </cliente>
</listaClientes>